//
//  AboutText.swift
//  AI • Scry
//
//  Created by Sam Kronick on 2/12/16.
//  Copyright © 2016 Disk Cactus. All rights reserved.
//

import Foundation

let aboutDiagramURL = NSURL(fileURLWithPath: NSBundle.mainBundle().pathForResource("diagram", ofType: "png")!)

let aboutStyle = "<!doctype html><head>" +
                 //"<meta name='viewport' content='width=300, user-scalable=no, initial-scale=1.0' />" +
                 "<style>* { color: white; font-family: HelveticaNeue-Light; font-size: 15pt; }" +
                 "body, html { overflow-x: hidden; } " +
                 ".tagline { font-style: italic; text-align: center; } " +
                 "a { background-color: blue; padding: 0.25em; padding-right: 0.25em; text-decoration: none; font-style: italic; }" +
                 "img { width: 98%; border: 1px dotted white; }" +
                 ".section { text-align: left;  font-style: italic; margin-bottom: 0em; } " +
                 ".howitworks { font-size: 11pt; }" +
                 ".howitworks a { font-size: 11pt; }" +
                 ".define, .define a { font-size: 11pt; font-style: italic; } " +
                 "</style></head><body>"
let aboutPageA = aboutStyle +
                 "<div class='tagline'>a remote viewing application powered by an alien psyche.</div>" +
"<p>Point your camera at the world around you. AI • Scry provides automatic textual descriptions of the objects it sees." +
                 //"<br><a href='aiscry://howitworks'>👉 How does it work?</a><p>" +
                 "<p>Adjust the \"Attention Aperature\" slider below to control the range of results.</p>" +
                 "<p class='section'>How does it work?</p>" +
                 "<img src='" + aboutDiagramURL.absoluteString + "'>" +
                 "<p class='howitworks'>AI • Scry transmits a 2D matrix of brightness values across time and space to a remote viewing algorithm housed in an undisclosed location somewhere in the state of Oregon.</p>" +
                 "<p class='howitworks'>The matrix is subject to rigorous mathematical analysis that scientists have yet to fully comprehend. The detector system has no direct knowledge of objects in the world (donuts, bananas, skateboards, wine glasses, etc) as we know them. Instead, the detector maps patterns received on the signal line to a sequence of word-choice probability distributions and assembles an output stream. The internal routing through this artificial neural network is largely meaningless to a human observer. Nonetheless, it works (sometimes)!</p>" +
                 "<p>With AI • Scry in your hand, you become an alien psychologist, probing the quirks, biases, impossibilities, and idiosyncrasies of this unknowable mind.</p>" +
                 "<p class='define'><a href='https://en.wikipedia.org/wiki/Scrying'>Scrying</a> is the practice of looking into a translucent ball or other material with the belief that things can be seen, such as spiritual visions, or for purposes of divination or fortune-telling ... Although scrying is most commonly done with a crystal ball, it may also be performed using any smooth surface, such as a bowl of liquid, a pond, or a crystal.</p>" +
                "<p class='howitworks'>Built with <a href='https://github.com/karpathy/neuraltalk2'>neuraltalk2</a> from Andrej Karpathy<br>Training <a href='http://mscoco.org/'>dataset</a> generated by anonymous, underpaid  humans working through Amazon Mechanical Turk<br><br>AI • Scry was designed & produced by <a href='http://diskcact.us'>💾🌵</a> in Oakland, CA</p>" +
                 "</body>"
